services:
  my-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3308:3308
  my-cache-server:
    image: redis
    ports:
      - 6379:6379